In [17]:
from mumax5 import World, Grid
import numpy as np

In [18]:
world = World( cellsize=(1e-9,1e-9,1e-9) )

magnet = world.addFerromagnet(  name = "magnet", 
                                grid = Grid((4,4,1)) )

In [19]:
m = magnet.magnetization.get()
m[2] = 1
magnet.magnetization.set(m)

In [20]:
magnet.anisU = (0,0,1)
magnet.ku1 = 7
h_anis = magnet.effective_field.eval()
print(h_anis)

[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[7. 7. 7. 7.]
   [7. 7. 7. 7.]
   [7. 7. 7. 7.]
   [7. 7. 7. 7.]]]]


6.0